### ISSUE TITLE
Uncaught Error: Firebase error. Please ensure that you spelled the name of your Firebase correctly

### ISSUE THREAD

**Issue by kbutler801** [fishdude/meteor-RTCMultiConnection#1]
hey there! thanks for all of the dev work! I recently started having this issue in meteor - where none of the sessions are publishing. In the console - it's logging...
"www.webrtc-experiment.com/firebase.js:1  Uncaught Error: Firebase error. Please ensure that you spelled the name of your Firebase correctly"

any ideas? thanks

**Comment by Aranguez** [comment]
I suggest you to verify your imports.
if you are using firestore (only) do not import 'firebase/database', just import 'firebase/firestore';

that was my problem

**Comment by Aranguez** [comment]
I suggest you to verify your imports.
If you are using firestore (only) do not import 'firebase/database', just import 'firebase/firestore';

That was my problem.
